version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      #USE_DB_ID: ${USE_DB_ID}
      #USE_JSON_PAYLOAD_AND_HEADERS: ${USE_JSON_PAYLOAD_AND_HEADERS}
  cdc-service:
    image: eventuateio/eventuate-cdc-service:latest
    ports:
      - "8099:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_CDC_PIPELINE_PIPELINE1_TYPE: eventuate-tram
      EVENTUATE_CDC_PIPELINE_PIPELINE1_READER: reader1
      EVENTUATE_CDC_PIPELINE_PIPELINE1_EVENTUATEDATABASESCHEMA: authmicrodb

      EVENTUATE_CDC_READER_READER1_TYPE: polling
      EVENTUATE_CDC_READER_READER1_DATASOURCEURL: jdbc:postgresql://postgres:5432/authmicrodb
      EVENTUATE_CDC_READER_READER1_DATASOURCEUSERNAME: ars
      EVENTUATE_CDC_READER_READER1_DATASOURCEPASSWORD: admin
      EVENTUATE_CDC_READER_READER1_DATASOURCEDRIVERCLASSNAME: org.postgresql.Driver
      EVENTUATE_CDC_READER_READER1_LEADERSHIPLOCKPATH: /eventuate/cdc/leader/common
      SPRING_PROFILES_ACTIVE: EventuatePolling
      JAVA_OPTS: -Xmx64m
  auth-service:
    build: ./auth
    ports:
      - "8082:8080"
    depends_on:
      - postgres
      - kafka
      - cdc-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/authmicrodb
      SPRING_DATASOURCE_USERNAME: ars
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: authmicrodb
  tutor-service:
    build: ./tutor
    ports:
      - "8084:8080"
    depends_on:
      - postgres
      - kafka
      - cdc-service
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/tutormicrodb
      SPRING_DATASOURCE_USERNAME: ars
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATE_DATABASE_SCHEMA: tutormicrodb
  api-gateway:
    build: ./apigateway
    ports:
      - "8080:8080"